name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # once per day (very safe)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Overview metrics
      - name: Generate overview metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CLASSIC_TOKEN }}
          filename: generated/overview.svg

          base: header, repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      # Language metrics
      - name: Generate language metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_CLASSIC_TOKEN }}
          filename: generated/languages.svg

          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_indepth: no
